import numpy as np
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
rank=np.linalg.matrix_rank(matrix)
deter=np.linalg.det(matrix)
trace=np.trace(matrix)
eigen=np.linalg.eigvals(matrix)
print(matrix)
print(rank)
print(deter)
print(trace)
print(eigen)